// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKII4kv6hXPi-QkXJlpolzW7GMsKc560w',
    appId: '1:1070699439998:web:abbd2646c0e3cef43ef52f',
    messagingSenderId: '1070699439998',
    projectId: 'alergenapp-882bb',
    authDomain: 'alergenapp-882bb.firebaseapp.com',
    storageBucket: 'alergenapp-882bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjON1GXrsUxphUZyPIrRRzFYzj0fRtkSM',
    appId: '1:1070699439998:android:7e0027dc05e3d6763ef52f',
    messagingSenderId: '1070699439998',
    projectId: 'alergenapp-882bb',
    storageBucket: 'alergenapp-882bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr7bYlaj6qYrHQk3x5UyvwKMq59AIJn2I',
    appId: '1:1070699439998:ios:25bc727d7a0420e63ef52f',
    messagingSenderId: '1070699439998',
    projectId: 'alergenapp-882bb',
    storageBucket: 'alergenapp-882bb.appspot.com',
    iosBundleId: 'com.example.alergenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr7bYlaj6qYrHQk3x5UyvwKMq59AIJn2I',
    appId: '1:1070699439998:ios:75e8959cfb9ecb593ef52f',
    messagingSenderId: '1070699439998',
    projectId: 'alergenapp-882bb',
    storageBucket: 'alergenapp-882bb.appspot.com',
    iosBundleId: 'com.example.alergenApp.RunnerTests',
  );
}
